name: Build
on:
  push:
    branches: [ main, feature/*, fix/* ]

env:
  MAVEN_REPOSITORY_USERNAME: ${{ secrets.OSSRH_USERNAME }}
  MAVEN_REPOSITORY_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
  MAVEN_SERVERS: |
    [{
      "id": "sonatype-central",
      "username": "${env.MAVEN_REPOSITORY_USERNAME}",
      "password": "${env.MAVEN_REPOSITORY_PASSWORD}"
    }]  

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
          server-id: sonatype-central
          server-username: MAVEN_REPOSITORY_USERNAME
          server-password: MAVEN_REPOSITORY_PASSWORD

      - name: Run maven tests
        run: mvn -B verify --file pom.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
      - name: Publish to maven central
        run: mvn --batch-mode deploy -Dmaven.test.skip=true
