name: Release version

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
      - name: Set up Docker
        run: |
          sudo apt update
          sudo apt install -y docker
      - name: Run maven tests
        run: mvn -B verify --file pom.xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          functionalities: network
          verbose: true
  release:
    if: contains( github.ref, 'main')
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v3
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
          server-id: sonatype-nexus-staging
          server-username: MAVEN_REPOSITORY_USERNAME
          server-password: MAVEN_REPOSITORY_PASSWORD
      - name: Release version
        uses: qcastel/github-actions-maven-release@master
        env:
          JAVA_HOME: /usr/lib/jvm/java-17-openjdk/
          MAVEN_REPOSITORY_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_REPOSITORY_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          SIGN_KEY: ${{ secrets.SIGN_KEY }}
          SIGN_KEY_ID: ${{ secrets.SIGN_KEY_ID }}
          SIGN_KEY_PASS: ${{ secrets.SIGN_KEY_PASS }}
        with:
          maven-args: "--batch-mode -Dmaven.test.skip=true"
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          release-branch-name: 'main'
