name: Release version
on: workflow_dispatch

permissions: write-all

env:
  MAVEN_REPOSITORY_USERNAME: ${{ secrets.OSSRH_USERNAME }}
  MAVEN_REPOSITORY_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
  SIGN_KEY: ${{ secrets.SIGN_KEY }}
  SIGN_KEY_ID: ${{ secrets.SIGN_KEY_ID }}
  SIGN_KEY_PASS: ${{ secrets.SIGN_KEY_PASS }}
  MAVEN_SERVERS: |
    [{
      "id": "sonatype-central",
      "username": "${env.MAVEN_REPOSITORY_USERNAME}",
      "password": "${env.MAVEN_REPOSITORY_PASSWORD}"
    }]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Run maven tests
        run: mvn -B verify --file pom.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
  release:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
          server-id: sonatype-central
          server-username: MAVEN_REPOSITORY_USERNAME
          server-password: MAVEN_REPOSITORY_PASSWORD
      - name: Release version
        uses: qcastel/github-actions-maven-release@master
        env:
          JAVA_HOME: /usr/lib/jvm/java-17-openjdk/
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          maven-args: "--batch-mode -Dmaven.test.skip=true"
          release-branch-name: ${{ github.ref_name }}
